### ISSUE TITLE
AlternatingRows - What am I missing?

### ISSUE THREAD

**Issue by sageteq** [martin9700/ConvertTo-AdvHTML#2]
Hello sir,

I followed the tutorial and everything works great except alternating rows. I get the following power shell error: ) : The "=" operator is missing after a named argument.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEqualsInNamedArgument

The code is below:
# SetAlertnateRows Specifics

Function Set-AlternatingRows {
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory,ValueFromPipeline)]
        [string]$Line,

```
    [Parameter(Mandatory)]
    [string]$CSSEvenClass,

    [Parameter(Mandatory)]
    [string]$CSSOddClass
)
Begin {
    $ClassName = $CSSEvenClass
}
Process {
    If ($Line.Contains("<tr><td>"))
    {   $Line = $Line.Replace("<tr>","<tr class=""$ClassName"">")
        If ($ClassName -eq $CSSEvenClass)
        {   $ClassName = $CSSOddClass
        }
        Else
        {   $ClassName = $CSSEvenClass
        }
    }
    Return $Line
}
```

}
# HTML Specifics

$Header = @"

<style>
TABLE {border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}
TH {border-width: 1px;padding: 3px;border-style: solid;border-color: black;background-color: #CAEAF6;}
TD {border-width: 1px;padding: 3px;border-style: solid;border-color: black;}
.odd  { background-color:#ffffff; }
.even { background-color:#dddddd; }
</style>

<title>
Exchange Free Disk Space Report
</title>
"@

**Comment by sageteq** [comment]
Good day Martin,

Hope all is well. 

Any feedback on the above? I tried and tried (for over a week) but cant figure out alternating rows and also the set color cell configuration to highlight a cell when a volume is below 50GB.

Your expertise and assistance appreciated.

Thank you,
Andrew

**Comment by martin9700** [comment]
Looks like there's some issue with your script. Here's what I did:

`$Data = Get-Service | Select -First 10

<your code from above here>

$html = $Data | ConvertTo-Html -Head $Header | Set-AlternatingRows -CSSEvenClass even -CSSOddClass odd

$html
`

And I got the desired results.  For help with your script I invite you to head over to the PowerShell forum on Spiceworks:  https://community.spiceworks.com/programming/powershell
But you'll need to post the portion of the code that's actually having the error as the above snippet you gave me isn't relevant.  Good luck!

**Comment by sageteq** [comment]
Thank you so much. I'll give that a shot.

Happy Father's Day!

-Andrew

**Comment by sageteq** [comment]
Hmmmm…where do I put that code in my script (below). Also posting this to spiceworks community.

[CmdletBinding()]
Param(
[Parameter(Mandatory=$false,Position=1)]
    [string[]]$ServerNames = $ServerNames  
)

# Set Alternating Rows

Function Set-AlternatingRows {
    [CmdletBinding()]
         Param(
             [Parameter(Mandatory=$True,ValueFromPipeline=$True)]
             [object[]]$HTMLDocument,

```
         [Parameter(Mandatory=$True)]
         [string]$CSSEvenClass,

         [Parameter(Mandatory=$True)]
         [string]$CSSOddClass
     )
 Begin {
     $ClassName = $CSSEvenClass
 }
 Process {
     [string]$Line = $HTMLDocument
     $Line = $Line.Replace("<tr>","<tr class=""$ClassName"">")
     If ($ClassName -eq $CSSEvenClass)
     {    $ClassName = $CSSOddClass
     }
     Else
     {    $ClassName = $CSSEvenClass
     }
     $Line = $Line.Replace("<table>","<table width=""50%"">")
     Return $Line
 }
```

}

# Get Volume information

Function Get-Volume ([string]$Path, [string]$ServerName) {
Do
{
$parent = $Path -Replace "[^\]*$"
$Volume = Get-WmiObject -Class Win32_Volume -ComputerName $ServerName -Filter ("Name = '" + $parent.Replace("\","\") + "'")
$Path = $parent -Replace ".$"
} While ($Volume -eq $null)
return $Volume
}

# Default template

remove-item "C:\ExchangeScripts\MBFreeDisk\MountFreeSpace.htm";
$file = New-Item -type file "C:\ExchangeScripts\MBFreeDisk\MountFreeSpace.htm";
$ServerNames = get-content -path "C:\ExchangeScripts\MBFreeDisk\WPMBServers.txt"
#$appName = $MyInvocation.MyCommand.Name.Substring(0,$MyInvocation.MyCommand.Name.LastIndexOf("."))
#$appPath = Split-Path $MyInvocation.MyCommand.Definition
#$outPath = $env:path += "C:\Scripts"
#$outPath = $env:temp
#$outFile = $outPath + "\" + $appName + ".csv"
#$FileDate = Get-Date -Format "yyyyMMdd"
$FilePath = "C:\ExchangeScripts\MBFreeDisk\"
$FileName = "FreeSpaceReport"
$FileType = ".csv"

# Prepare output collection

$return = @()

# Convert dates to WMI CIM dates

$Tc = [System.Management.ManagementDateTimeconverter]
$evtTimeStart =$Tc::ToDmtfDateTime((Get-Date).AddDays(-1).Date)

# Create two calculated properties for InsertionStrings values

$evtDb = @{Name="Db";Expression={$_.InsertionStrings[1]}}
$evtFreeMB = @{Name="FreeMB";Expression={[int]$_.InsertionStrings[0]}}

# Loop through Exchange Servers

ForEach ($ServerName in $ServerNames)
{

# Initialize counter for progress bar

$counter = 0

# Loop through Exchange Server Databases

$DBs = Get-MailboxDatabase -Server $ServerName | Sort-Object $_.EdbFilePath.PathName
ForEach ($Db in $DBs)
{

# Get Transaction LOGs volume information (both Logical Drive and Mount Point): Name, Capacity, Free Space

If ((Get-ExchangeServer $ServerName).AdminDisplayVersion -like "Version 8*") {

# Exchange 2007

$SG = Get-StorageGroup -Identity $($Db.StorageGroup)
$logPath = "$($SG.LogFolderPath)\"
$circularLogging = $($SG.CircularLoggingEnabled)
} Else {
$logPath = "$($Db.LogFolderPath)\"
$circularLogging = $($Db.CircularLoggingEnabled)
}
$LogVolume = Get-Volume -Path $logPath -ServerName $ServerName
$logVolumeCapacity = ($LogVolume.Capacity / 1GB)
$logVolumeFreeSpace = ($LogVolume.FreeSpace / 1GB)

# Increase counter for progress bar

$counter++

# Display progress bar

Write-Progress -Activity "Getting Database information" -Status "Processing Database $Db" -PercentComplete (100 \* ($counter/@($DBs).count))

# Get DB volume information (both Logical Drive and Mount Point): Name, Capacity, Free Space

$dbFilePath = $Db.EdbFilePath.PathName
$DbVolume = Get-Volume -Path $dbFilePath -ServerName $ServerName

# Get DBs file size information

$DbFile = Get-WmiObject -Class CIM_LogicalFile -ComputerName $ServerName -Filter ("Name = '" + $dbFilePath.Replace("\","\") + "'")

# Count DB mailboxes

#$mailboxCount = Get-MailboxStatistics -Database $Db.Identity | Where-Object {$_.DisconnectDate -eq $null -and $_.ObjectClass -eq "Mailbox"} | Measure-Object
$mailboxCount = Get-MailboxStatistics -Database $Db.Identity | Where-Object {$_.DisconnectDate -eq $null -and $_.ObjectClass -NotMatch "(SystemAttendantMailbox|ExOleDbSystemMailbox)"} | Measure-Object

# Count disconnected DB mailboxes

$disconnectedMailboxCount = Get-MailboxStatistics -Database $Db.Identity | Where-Object {$_.DisconnectDate -ne $null} | Measure-Object

# Get latest DB free space information from Application Events Log (Event ID 1221)

$dbName = $Db.Identity.Parent.Name + "\" + $Db.Identity.Name
$DbFreeSpace = Get-WMIObject Win32_NTLogEvent -ComputerName $ServerName -Filter `
"LogFile = 'Application' AND EventCode = 1221 AND TimeWritten > '$evtTimeStart'" |`
Where-Object {$_.InsertionStrings[1] -eq $dbName} | Select-Object $evtDb, $evtFreeMB -First 1 | Sort-Object TimeWritten, FreeMB –Unique –Descending
$dbVolumeCapacity = ($DbVolume.Capacity / 1GB)
$dbVolumeFreeSpace = ($DbVolume.FreeSpace / 1GB)
$dbFreeSpace = ($DbFreeSpace.FreeMB / 1KB)
$Obj = New-Object PSObject
        $Obj | Add-Member NoteProperty -Name "ServerName" -Value $ServerName
$Obj | Add-Member NoteProperty -Name "DbVolumeName" -Value $DbVolume.Name
$Obj | Add-Member NoteProperty -Name "DbVolumeCapacity(GB)" -Value ("{0:n2}" -f $dbVolumeCapacity)
$Obj | Add-Member NoteProperty -Name "DbVolumeFreeSpace(GB)" -Value ("{0:n2}" -f $dbVolumeFreeSpace)
$Obj | Add-Member NoteProperty -Name "DbVolumeFree%" -Value ("{0:n2}" -f ($dbVolumeFreeSpace / $dbVolumeCapacity \* 100))
$Obj | Add-Member NoteProperty -Name "DbVolumeTotalFree(GB)" -Value ("{0:n2}" -f ($dbVolumeFreeSpace + $dbFreeSpace))
$Obj | Add-Member NoteProperty -Name "DatabaseName" -Value $Db.Identity
$Obj | Add-Member NoteProperty -Name "DbFileSize(GB)" -Value ("{0:n2}" -f ($DbFile.FileSize / 1GB))
#$Obj | Add-Member NoteProperty -Name "DbFreeSize(GB)" -Value ("{0:n2}" -f $dbFreeSpace)
#$Obj | Add-Member NoteProperty -Name "IssueWarningQuota(GB)" -Value ("{0:n2}" -f ($Db.IssueWarningQuota.Value.ToBytes() / 1GB))
#$Obj | Add-Member NoteProperty -Name "ProhibitSendQuota(GB)" -Value ("{0:n2}" -f ($Db.ProhibitSendQuota.Value.ToBytes() / 1GB))
#$Obj | Add-Member NoteProperty -Name "ProhibitSendReceiveQuota(GB)" -Value ("{0:n2}" -f ($Db.ProhibitSendReceiveQuota.Value.ToBytes() / 1GB))
$Obj | Add-Member NoteProperty -Name "UserMailboxCount" -Value $mailboxCount.Count
$Obj | Add-Member NoteProperty -Name "DisconnectedMailboxCount" -Value $disconnectedMailboxCount.Count
#$Obj | Add-Member NoteProperty -Name "LogVolumeName" -Value $LogVolume.Name
#$Obj | Add-Member NoteProperty -Name "LogVolumeCapacity(GB)" -Value ("{0:n2}" -f $logVolumeCapacity)
#$Obj | Add-Member NoteProperty -Name "LogVolumeFreeSpace(GB)" -Value ("{0:n2}" -f $logVolumeFreeSpace)
#$Obj | Add-Member NoteProperty -Name "LogVolumeFree%" -Value ("{0:n2}" -f ($logVolumeFreeSpace / $logVolumeCapacity \* 100))
#$Obj | Add-Member NoteProperty -Name "OfflineAddressBook" -Value $Db.OfflineAddressBook
#$Obj | Add-Member NoteProperty -Name "PublicFolderDatabase" -Value $Db.PublicFolderDatabase
#$Obj | Add-Member NoteProperty -Name "CircularLoggingEnabled" -Value $circularLogging
$return += $Obj
}
Write-Progress -Activity "Getting Database information" -Status "Completed" -Completed
}
#Convert To HTML

# Export output to csv

#$return | Export-Csv -Path ($FilePath+$FileName+$FileType) -Delimiter "," -Force -noTypeInformation -Encoding UTF8

#HTML Specifics
$Header = @"

<style>
TABLE {border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}
TH {border-width: 1px;padding: 3px;border-style: solid;border-color: black;background-color: #CAEAF6;}
TD {border-width: 1px;padding: 3px;border-style: solid;border-color: black;}
.odd  { background-color:#ffffff; }
.even { background-color:#dddddd; }
</style>

"@

Write-Output $return | Select-Object "ServerName", "DbVolumeName", "DbVolumeCapacity(GB)", "DbVolumeFreeSpace(GB)", "DbVolumeFree%", "DatabaseName", "DbFileSize(GB)", "UserMailboxCount", "DisconnectedMailboxCount" | Sort “DBVolumeFreeSpace(GB)” | ConvertTo-HTML -Head $Header | Set-AlternatingRows 
-CSSEvenClass even -CSSOddClass odd | Out-File $file

From:  MartinPugh
Reply-To:  martin9700/ConvertTo-AdvHTML
Date:  Saturday, June 18, 2016 at 6:56 AM
To:  martin9700/ConvertTo-AdvHTML
Cc:  Andrew McCalla, Author
Subject:  Re: [martin9700/ConvertTo-AdvHTML] AlternatingRows - What am I missing? (#2)

Looks like there's some issue with your script. Here's what I did:

`$Data = Get-Service | Select -First 10

$html = $Data | ConvertTo-Html -Head $Header | Set-AlternatingRows -CSSEvenClass even -CSSOddClass odd

$html
`

And I got the desired results.  For help with your script I invite you to head over to the PowerShell forum on Spiceworks:  https://community.spiceworks.com/programming/powershell
But you'll need to post the portion of the code that's actually having the error as the above snippet you gave me isn't relevant.  Good luck!
